# Ideal Customer Profile for "Project Phoenix"

# 1. Firmographics (Company-level data)
firmographics:
  target_industries:
    - "Software"
    - "E-commerce"
    - "Finance"
    - "Cybersecurity"
  employee_count:
    min: 100
    max: 2000
  locations:
    - "Bengaluru"
    - "Hyderabad"
    - "Pune"
    - "Gurugram"
    - "Mumbai"

# 2. Persona (Contact-level data)
persona:
  job_titles:
    - "Head of Sales"
    - "Head of Marketing"
    - "Product Manager"
    - "CTO"
    - "CEO"
    - "Data Scientist"
  seniority_level:
    - "Manager"
    - "Head"
    - "Director"
    - "C-Level"
  excluded_titles:
    - "Intern"
    - "Executive"
    - "Assistant"
    - "Sales Executive"

technographics:
  uses_crm:
    - "HubSpot"
    - "Zoho CRM"
    - "Salesforce"
  uses_analytics:
    - "Google Analytics"
    - "Mixpanel"

# 4. Scoring Model (To rank leads instead of just matching)
scoring_weights:
  # Base score for any lead
  base_score: 10
  # Add points for matching criteria
  industry_match: 25
  employee_count_within_range: 15
  location_match: 20
  job_title_match: 20
  # crm_match: 25
  # Subtract points for negative signals
  is_excluded_title: -50